### ISSUE TITLE
The MIA issue

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Nomic#10]
@VermillionAzure said he wanted to play... but basically hasn't shown face yet... are we still counting him as actively playing, are we still going to wait for him?

**Comment by rmartinho** [comment]
http://chat.stackoverflow.com/transcript/message/36055135#36055135

**Comment by shoooe** [comment]
I'd say no: http://chat.stackoverflow.com/transcript/message/36055135#36055135

**Comment by thecoshman** [comment]
Right so, we can leave him in the project, but at least we know now. If only there was some way for players to properly join and leave the game...  hint hint
