### ISSUE TITLE
§304 - Repeal of §209

### ISSUE THREAD

**Issue by shoooe** [LoungeCPP/Nomic#13]
Rule §209 imposes a strict number of mutable rules:

> 209. At no time may there be more than 25 mutable rules.

 While I do agree there should be a limit to the number of rules in the future, this is:

 - too small
 - doesn't take into account the size of each rule (see §207 vs §212)
 - can block future interactions

Therefore I propose to repeal this rule.

**Comment by rmartinho** [comment]
Why did you vote against, @thecoshman?

**Comment by rmartinho** [comment]
Why did you vote against, @thecoshman?

**Comment by thecoshman** [comment]
I don't see any reason to remove this limit now, and actually kinda like it, it helps prevent things getting over complex. Not that I have to tell you my reasoning :P
