### ISSUE TITLE
§305 Enactment - Participation through inaction

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Nomic#14]
Yes, trying to for this one again :smile: 

Currently, if a player is not around, we must wait indefinitely for them to take part, which means the game can come to a halt for everyone. As such, I want to provide an escape mechanism that can allow us to get around this problem.

> From the moment a decisions is put to the vote, all players have seven days in which to express their vote explicitly. If after the allotted time they have not explicitly cast their vote, then they are presumed to have participated through an act of silent protest and implicate cast of a "no vote".
>
> This rules applies to any voting process unless other wise explicitly forbidden by stating, to the effect, that this rule does not apply, that players must "actively participate" or that the votes must be "explicitly cast".

Hopefully, this rule will never need to actually get used, but as I said before, I don't want to see the game be brought to a dead lock simply because a player isn't active.

I am aware that this is close to interfering with rule 105, but I think this is acceptable, players are still "participating", they are just doing so through an inaction. If it is considered interfering, then this would just apply to other voting processes, and thus for now at least, wouldn't be of much use.

I think the only objection @Jefffrey had last time was the ability to extend the vote period, so that is gone and we'll just settle on the 7 days for now. Hopefully @rmartinho does't feel that this amendment ruins the proposal.

**Comment by shoooe** [comment]
Put is as a proposal and we'll see.

**Comment by shoooe** [comment]
I'm sorry but I vote against. In the current situation we are 3 and somebody missing in action is and should be a huge deal. Moreover if somebody were to, for example, have internet down for a while, other players might kick him out quickly from the game or pass rules that are unfavourable to him. This is especially true as unanimity stops being a requirement the next circle of turns.
