### ISSUE TITLE
§301 / Amendment of §202

### ISSUE THREAD

**Issue by shoooe** [LoungeCPP/Nomic#4]
I propose to change the following rule:

> **202.** One turn consists of two parts in this order:
> 1. proposing one rule-change and having it voted on, and
> 2. throwing one die once and adding the number of points on its face to one's score.
>
> In mail and computer games, instead of throwing a die, players subtract 291 from the ordinal number of their proposal and multiply the result by the fraction of favorable votes it received, rounded to the nearest integer. (This yields a number between 0 and 10 for the first player, with the upper limit increasing by one each turn; more points are awarded for more popular proposals.)

to the following:

> **301.** One turn consists of the following steps in the given order:
> 1. proposing one rule-change by creating an issue in Github with the label "proposal" and title `§[Proposal number] / [Descriptive title]` where `[Proposal number]` is the number of the proposal and `[Descriptive title]` is a descriptive title assigned to the proposal by the author
> 2. having it voted on
> 3. adding 10 points to the author of the proposal multiplied by the fraction of favourable votes it received, rounded to the nearest integer. This yields a number between 0 and 10.

This begins to formalise Github as the platform and the procedures to follow in order to play correctly. Moreover the voting system is changed so that the number of the proposal doesn't count in rewarding points, making it easier in the future to change the rule reference format.

**Comment by rmartinho** [comment]
I'd make it more explicit about where on GitHub.

**Comment by shoooe** [comment]
I guess now that you have commented on it, the body of the proposal is locked.

**Comment by rmartinho** [comment]
Why so? See §111.

**Comment by thecoshman** [comment]
The proposal is only locked when you decide to have people start voting on it. There is currently nothing saying when you or how you do that. For example, I could decide to vote right now and that vote would be stick, unless  you alter the proposal, in which case my vote is 'void' and I would need to recast it. Personally, I don't think §111 is that relevant in this regard, I think it's more covered by §106, it is the state of the proposal as it is when voted on that matters.

As for this proposal though, are you not changing two things; the way a proposal is formed and also how points are awarded. This I'd see as falling under §111, but maybe that is about a proposal not being allowed to amend multiple rules.

Regarding the points, I think a lot of rules, especially immutable rules are tied to the idea of rules being numbered. So perhaps consider that.

**Comment by rmartinho** [comment]
>  I think it's more covered by §106, it is the state of the proposal as it is when voted on that matters.

§111 is relevant because the only rule that lets you alter a proposal after proposing it. No one mentioned votes until you did.

> For example, I could decide to vote right now and that vote would be stick, unless you alter the proposal,

See §111. You can't vote until the person making the proposal says so.

**Comment by thecoshman** [comment]
Ah, you are right about the voting time frame being defined (as undefined) in §111. I bring up §106 as that also covers the concept of 'locking' a proposal and determining what exactly goes into effect. Without §106, you could potentially have a proposal approved, but then change it after the voting, but that is explicitly restricted by §106.

**Comment by shoooe** [comment]
You are right about the two rule change into one. So let's finalize points first.

> **301.** One turn consists of the following steps in the given order:
> 1. proposing one rule-change
> 2. having it voted on
> 3. adding 10 points to the author of the proposal multiplied by the fraction of favourable votes it received, rounded to the nearest integer
