### ISSUE TITLE
Reactions for votes?

### ISSUE THREAD

**Issue by shoooe** [LoungeCPP/Nomic#5]
I wonder if it's possible to lock rections to posts.

**Comment by Jefffrey** [comment]
Apparently no

**Comment by shoooe** [comment]
Oh, locking the conversation actually locks the votes.

**Comment by rmartinho** [comment]
I like it.

**Comment by thecoshman** [comment]
So for now at least, a gentleman's agreement to use just the +1 and -1 for the vote.

**Comment by shoooe** [comment]
This is being used correctly. I'm closing this issue.
