### ISSUE TITLE
How to finalise proposal ready for vote

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Nomic#6]
I think it'd be good to agree, at least informally for now, on how to do the voting. I'd suggest that the player make a final post for what exactly people will vote on, add a label like "ready to vote" and then people should no longer post any comments, at this point, they just vote.

I think this is better than editing the original post as you can read through how we got to this and any justification and the final post is just the end state, "this is exactly what we are voting for, yay or nay"

**Comment by shoooe** [comment]
The original idea was to use the label `draft` for drafts and `proposal` for the finalized draft that should be voted on.

**Comment by thecoshman** [comment]
But again, I would like a very clear and precise "this is the rule text that would go into effect"

**Comment by shoooe** [comment]
It seem that at the moment the label `proposal` has been used successfully to define proposals that are ready to be voted on. I'm closing this for the moment to keep as opened issues only relevant and active discussions.
