### ISSUE TITLE
§301 / Amendment of 202

### ISSUE THREAD

**Issue by shoooe** [LoungeCPP/Nomic#7]
I propose to change the following rule:

> **202.** One turn consists of two parts in this order:
> 1. proposing one rule-change and having it voted on, and
> 2. throwing one die once and adding the number of points on its face to one's score.
>
> In mail and computer games, instead of throwing a die, players subtract 291 from the ordinal number of their proposal and multiply the result by the fraction of favorable votes it received, rounded to the nearest integer. (This yields a number between 0 and 10 for the first player, with the upper limit increasing by one each turn; more points are awarded for more popular proposals.)

to the following:

> **301.** One turn consists of the following steps in the given order:
> 1. proposing one rule-change
> 2. having it voted on
> 3. adding 10 points to the author of the proposal multiplied by the fraction of favourable votes it received, rounded to the nearest integer

Please vote using a reaction with a thumb up for "yes" and a thumb down for "no" according to [this](https://github.com/LoungeCPP/Nomic/issues/5).

**Comment by rmartinho** [comment]
Damn, can't react from OctoDroid. :(

**Comment by thecoshman** [comment]
@rmartinho any chance you could vote on this at some point...

**Comment by shoooe** [comment]
The proposal is rejected with 1 vote against by @thecoshman
