### ISSUE TITLE
Player Order

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Nomic#8]
We currently a rule that states we rotate based on surname, but those aren't public for all. I'm also not 100% sure who is playing, I thought @VermillionAzure joined us... but he didnt vote.

**Comment by shoooe** [comment]
@VermillionAzure Said he is busy. He is technically playing but his vote was irrelevant since you voted against and there's unanimity for now. His is eligible to vote, and he will have to vote, but to speed things up I already rejected the proposal in order for the next one to be proposed.

**Comment by shoooe** [comment]
We fucked up with regards to order. Alphabetically it should have been:

 - rmartinho
 - Shoe
 - thecoshman
 - VermillionAzure

And even surname wise rmartinho was before me. I suggest that for this turn we agree on a order and then we keep the alphabetical order based on usernames.

**Comment by thecoshman** [comment]
We've only taken one player turn, so as long as we continue alphabetically from here, I don't see any issue. 

As such, I believe that it is my turn to propose a rule change.

Strictly speaking though, rule 105 (iirc) states that every player must participate in voting, we are not allowed to skip their vote. I guess really it can expose information about how to vote for/against others

**Comment by shoooe** [comment]
Yeah sure, we have to explain to @VermillionAzure how it all works and make him vote for 301.

**Comment by thecoshman** [comment]
Well for now, whilst it's still unanimous voting, I don't think that really matters. But he should pay attention really and know what people are voting for/against
