### ISSUE TITLE
§302 Enactment - Participation through inaction

### ISSUE THREAD

**Issue by thecoshman** [LoungeCPP/Nomic#9]
Currently, if a player is not around, we must wait indefinitely for them to take part, which means the game can come to a halt for everyone. As such, I want to provide an escape mechanism that can allow us to get around this problem.

> From the moment a decisions is put to the vote, all players have seven days in which to express their vote explicitly. If after the allotted time they have not explicitly cast their vote, then they are presumed to have participated through an act of silent protest and implicate cast a "no vote".
> 
> A player may request an extension to this time limit, this can even be done before the decision is even put to vote. Other players must respect this request unless they believe it is excessive in which case they can invoke judgement. If an extension is granted, it applies to all players.
>
> This rules applies to any voting process unless other wise explicitly forbidden by stating, to the effect, that this rule does not apply, that players must "actively participate" or that the votes must be "explicitly cast".

Hopefully, this rule will never need to actually get used, but as I said before, I don't want to see the game be brought to a dead lock simply because a player isn't active.

I have given what I think is generous time for players to vote and provided a way for it to be extended if required, but again, without letting a player lock up the game (for example, requesting a 10 year extension to the voting period can be rejected). I have applied this to anything that would require players to vote, but allowed rules to exempt them selves (though I guess I didn't need to explicitly do this, but It's easier for other rules to do so).

I am aware that this is close to interfering with rule 105, but I think this is acceptable, players are still "participating", they are just doing so through an inaction. If it is considered interfering, then this would just apply to other voting processes, and thus for now at least, wouldn't be of much use.

I was tempted to add something about tracking so that we could look to apply penalties if players keep failing to play, but I think that's something that is best though out separately; the focus here is just allowing the game to keep moving.

**Comment by thecoshman** [comment]
@rmartinho @Jefffrey @VermillionAzure so erm... any feedback about this, or shall I just put it to vote?

**Comment by shoooe** [comment]
I'm not sure the judgment thingy is worth it. I mean if they can tell you that they need more time they can usually just read the rule and vote already.

I can foresee it being a problem in the future maybe, if we allow parallel proposals, but as it currently stands it's too subjective in my opinion. 7 days should be good enough.

I would be also fine with implementing penalty on delayed voting, but yes, maybe in another proposal.

**Comment by rmartinho** [comment]
This looks ok. s/caste/cast

**Comment by thecoshman** [comment]
@Jefffrey My thinking is that it only takes a moment to pop and say "Hey guys, busy this week, so can I get back to this later" but properly thinking about a proposal can take some time, especially if they get more complex and intertwined.

**Comment by shoooe** [comment]
Voted

**Comment by rmartinho** [comment]
I guess this means it's rejected.
